version: "3.9"

services:
  website:
    image: nginx:1.21.6-alpine
    container_name: bch-webseite
    volumes:
      - ${PWD}:/usr/share/nginx/html
      - ${PWD}/nginx.conf:/etc/nginx/conf.d/default.conf
      - ${PWD}/entrypoint.sh:/entrypoint.sh
    entrypoint: ["sh", "entrypoint.sh"]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bch-website.rule=Host(`bigchungus.test`)"
      - "traefik.http.routers.bch-website.tls=true"
      - "traefik.http.routers.bch-website.entrypoints=websecure"
      - "traefik.http.routers.bch-website.tls.certresolver=resolver"
      - "traefik.http.services.bch-website.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik"

    networks:
      - traefik

networks:
  traefik:
    external: true
    name: traefik
